version: '3'
services:
  nodered:
    image: nodered/node-red:3.0.2-14
    container_name: nodered
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - /mnt/disk-001/volumes/nodered/data:/data

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - /mnt/disk-001/volumes/influxdb/var/lib/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:10.0.1
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '1000'
    ports:
      - '3000:3000'
    volumes:
      - '/mnt/disk-001/volumes/grafana/var/lib/grafana:/var/lib/grafana'

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/config:/mqtt/config
      - ./volumes/mosquitto/log:/mqtt/log
      - ./volumes/mosquitto/data/:/mqtt/data

